/*
 오라클의 RANK 함수
 예제: 고객- 상품별 최대 구매 금액을 구하고 해당 상품코드 조회하기
 	ㄴ고객ID로 1차 그룹화, 고객 내에서 상품코드로 2차 그룹화
 **/
--준비) MINA에게 구매 이력이 있는 상품을 한번 더 구매시킴
INSERT INTO TBL_BUY tp2  VALUES(BUY_PK_SEQ.NEXTVAL, 'mina012','JINRMn5',13,'2024-01-26');
SELECT *
FROM TBL_BUY TB, TBL_PRODUCT TP
WHERE TB.PCODE = TP.PCODE;

--1) GROUP BY
SELECT TB.CUSTOMID , TB.PCODE ,SUM(TP.PRICE*TB.QUANTITY) "총합"    --가격*수량에 대한 그룹화 함수 SUM 실행 -진라면 갯수 합해짐
FROM TBL_BUY TB, TBL_PRODUCT TP
WHERE TB.PCODE = TP.PCODE
GROUP BY TB.CUSTOMID, TB.PCODE ;

--2) 1번 결과 정렬
SELECT TB.CUSTOMID , TB.PCODE ,SUM(TP.PRICE*TB.QUANTITY) MONEY 
FROM TBL_BUY TB, TBL_PRODUCT TP
WHERE TB.PCODE = TP.PCODE
GROUP BY TB.CUSTOMID, TB.PCODE 
ORDER BY TB.CUSTOMID, MONEY DESC 


--같은 수준의 SELECT에서는 AS로 호출 불가능
--3)1번에 RANK 함수 적용
SELECT TB.CUSTOMID , TB.PCODE ,SUM(TP.PRICE*TB.QUANTITY) MONEY, 
RANK() OVER (PARTITION BY TB.CUSTOMID ORDER BY SUM(TP.PRICE*TB.QUANTITY)DESC) "RANK"
--PARTITION BY ->GROUP BY랑 비슷함.. 적힌 것끼리 묶음
--OVER()안에는 어떤 컬럼으로 정렬해서 순위를 매기는지에 대한 내용
--RANK() OVER (ORDER BY SUM(TP.PRICE*TB.QUANTITY)DESC) "RANK"  --그룹화된  MONEY 순위
FROM TBL_BUY TB, TBL_PRODUCT TP
WHERE TB.PCODE = TP.PCODE
GROUP BY TB.CUSTOMID, TB.PCODE ;

--4) 3번을 서브쿼리로 하여 RANK=1인 조건을 적용해보기
WITH CUSTOMSALE
AS
(SELECT TB.CUSTOMID , TB.PCODE ,SUM(TP.PRICE*TB.QUANTITY) MONEY, 
RANK() OVER (PARTITION BY TB.CUSTOMID ORDER BY SUM(TP.PRICE*TB.QUANTITY)DESC) "RANK"
FROM TBL_BUY TB, TBL_PRODUCT TP
WHERE TB.PCODE = TP.PCODE
GROUP BY TB.CUSTOMID, TB.PCODE 
)
SELECT CUSTOMSALE.CUSTOMID,CUSTOMSALE.PCODE,CUSTOMSALE.MONEY,CUSTOMSALE.RANK
FROM CUSTOMSALE
WHERE RANK =1;












WITH CUSTOMSALE
AS
		(SELECT TB.CUSTOMID , TB.PCODE ,SUM(TP.PRICE*TB.QUANTITY) MONEY, 
		RANK() OVER (PARTITION BY TB.CUSTOMID ORDER BY SUM(TP.PRICE*TB.QUANTITY)DESC) "RANK"
		FROM TBL_BUY TB, TBL_PRODUCT TP
		WHERE TB.PCODE = TP.PCODE
		GROUP BY TB.CUSTOMID, TB.PCODE 
		)
	SELECT CUSTOMSALE.CUSTOMID,CUSTOMSALE.PCODE,CUSTOMSALE.MONEY,CUSTOMSALE.RANK,TBL_PRODUCT.PNAME 
	FROM CUSTOMSALE, TBL_PRODUCT
	WHERE RANK =1
	HAVING BY CUSTOMSALE.PCODE = TBL_PRODUCT.PNAME ;



