CREATE TABLE TBL_JAVAWORD(
ENGLISH VARCHAR2(100) UNIQUE NOT null, 
KOREAN NVARCHAR2(100) NOT null, 
STEP NUMBER(1) CHECK (step BETWEEN 1 AND 4),   --check () 괄호 필수
IDX NUMBER PRIMARY key(8)); --유니크와 낫널





INSERT INTO TBL_JAVAWORD
(ENGLISH, KOREAN, STEP, IDX)
VALUES('list', '목록', 1, 1);
INSERT INTO TBL_JAVAWORD
(ENGLISH, KOREAN, STEP, IDX)
VALUES('main', '주요한', 1, 2);
INSERT INTO TBL_JAVAWORD
(ENGLISH, KOREAN, STEP, IDX)
VALUES('static', '정적인', 2, 3);
INSERT INTO TBL_JAVAWORD
(ENGLISH, KOREAN, STEP, IDX)
VALUES('remove', '삭제하다', 2, 4);
INSERT INTO TBL_JAVAWORD
(ENGLISH, KOREAN, STEP, IDX)
VALUES('interface', '접점', 1, 5);


--새로운 연산자
INSERT INTO TBL_JAVAWORD
VALUES('constraint', '제약사항',3, 5);

INSERT INTO TBL_JAVAWORD
VALUES('order','순서', 1, 9);

--모든 컬럼을 추가할 경우에는 걸럼명을 제외할 수 있음 
--NSERT INTO TBL_JAVAWORD
--VALUES('interface', '접점', 1, 5);

SELECT *FROM TBL_JAVAWORD tj 
WHERE ENGLISH LIKE '%t';

SELECT *FROM TBL_JAVAWORD tj WHERE IDX =2 OR IDX =5 OR IDX =9;
SELECT *FROM TBL_JAVAWORD 
	WHERE IDX IN (2,5,9); 

SELECT *FROM TBL_JAVAWORD 
WHERE IDX >=2 AND IDX <=5;
SELECT *FROM TBL_JAVAWORD 
WHERE IDX BETWEEN 2 AND 5;

ALTER TABLE TBL_JAVAWORD MODIFY ENGLISH NOT NULL;

--SELECET 컬럼명1, 2.. FROM 테이블명
--					WHERE 컬럼명 = 값
--					ORDER BY 컬럼명1, 컬럼명2 [DESC]-내림차순 , [ASC] - 오름차순
		-->컬지정된 컬럼명으로 정렬.. 컬럼명1이 같은 값이면 컬럼명2로 정렬

SELECT *FROM TBL_JAVAWORD 
	WHERE IDX IN (2,5,9)
	ORDER BY IDX ; 

SELECT *FROM TBL_JAVAWORD;

INSERT INTO TBL_JAVAWORD
VALUES('pirvate','개인적인', 1, 6);

SELECT *FROM TBL_JAVAWORD 
	WHERE IDX IN (2,5,9) 
	ORDER BY IDX , KOREAN ; --idx 1차 정렬컬럼, korean 2차 정렬 컬럼
	
	
	
	
	--단어장 테이블에 제약조건을 적용해서 다시 만들어보자
